### ISSUE TITLE
Minor Suggestions

### ISSUE THREAD

**Issue by ha0ye** [aaarchmiller/template_project#1]
Not sure if you prefer these here or as a pull request, so let me know.

For Rmarkdown, I use
> date: '`r format(Sys.Date(), "%B %d, %Y")`'
in the YAML header to get R to insert the current date at time of knitting.

I'd also suggest adding a LICENSE file to the project / repo so that there are clear guidelines for other people using this template.

Finally, maybe add some instructions to README about forking and cloning?

**Comment by aaarcher-usgs** [comment]
Thanks! 

I tried the YAML header change, it didn't work. If you can, could you do it as a pull request? I may have just typed it in wrong? 

When I added it, it wouldn't knit to Word and it knit the text verbatim to the pdf.

Thanks for the other suggestions, I will update with license and some forking info, although I never fork anything so I don't really know what instructions will be useful. Do you have an example?

**Comment by ha0ye** [comment]
I will take a look - I know I've had issues with knitr reformatting the quotes if you switch the output type.

I'll search for some instructions on forking - it's mainly for people who might want to customize your template for their own repeated use vs. doing a clone and modifying for each project.
